name: Render Helm Chart

on:
  push:
    branches:
      - develop

jobs:
  render-helm-templates:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Render Helm Template for Development
      run: |
        echo "Rendering Helm template for 'dev' environment..."
        helm template --debug myapp . -f values.yaml -f values-development.yaml

    - name: Render Helm Template for Production
      run: |
        echo "Rendering Helm template for 'prod' environment..."
        helm template --debug myapp . -f values.yaml -f values-production.yaml